-- ---------------------------------
-- 
-- CODIGO GERADOR DA BASES DE DADOS
-- TABELAS E ATRIBUTOS
--
------------------------------------

-- ---------------------------------
-- CRIACAO BASE DE DADOS
-- ---------------------------------
CREATE SCHEMA IF NOT EXISTS GEVENTOS;

-- ---------------------------------
-- SELECAO BASE DE DADOS
-- ---------------------------------
USE GEVENTOS;

-- ---------------------------------
-- CRIACAO TABELA - MORADA
-- ---------------------------------
CREATE TABLE IF NOT EXISTS MORADA(
IDMORADA INT NOT NULL,
RUA VARCHAR(50) NOT NULL,
PORTA VARCHAR(50) NOT NULL,
CODIGOPOSTAL VARCHAR(50) NOT NULL,
LOCALIDADE VARCHAR(50) NOT NULL,
PRIMARY KEY(IDMORADA)
);

-- ---------------------------------
-- CRIACAO TABELA - CLIENTE
-- ---------------------------------
CREATE TABLE IF NOT EXISTS CLIENTE(
IDCLIENTE INT NOT NULL,
NOME VARCHAR(75) NOT NULL,
EMAIL VARCHAR(50),
IDADE INT NOT NULL,
IDMORADA INT NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
PRIMARY KEY (IDCLIENTE),
FOREIGN KEY(IDMORADA) REFERENCES MORADA(IDMORADA)
);

-- ---------------------------------
-- CRIACAO TABELA - AGENTE
-- ---------------------------------
CREATE TABLE IF NOT EXISTS AGENTE(
IDAGENTE INT NOT NULL,
NOME VARCHAR(75) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
DESIGNACAO VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
PRIMARY KEY(IDAGENTE)
);

-- ---------------------------------
-- CRIACAO TABELA - EVENTO
-- ---------------------------------
CREATE TABLE IF NOT EXISTS EVENTO(
IDEVENTO INT NOT NULL,
DESIGNACAO VARCHAR(50) NOT NULL,
DATA DATETIME NOT NULL,
LOTACAO INT NOT NULL,
VALORALUGUER DECIMAL(8,2) NOT NULL,
ESTADOPAGAMENTOLOCAL BINARY(1) NOT NULL,
IDMORADA INT NOT NULL,
PRIMARY KEY(IDEVENTO),
FOREIGN KEY(IDMORADA) REFERENCES MORADA(IDMORADA)
);

-- ---------------------------------
-- CRIACAO TABELA - AGENTEEVENTO
-- ---------------------------------
CREATE TABLE IF NOT EXISTS AGENTEEVENTO(
IDAGENTE INT NOT NULL,
IDEVENTO INT NOT NULL,
PRECOAGENTE DECIMAL(8,2) NOT NULL,
ESTADOPAGAMENTOAGENTE BINARY(1) NOT NULL,
PRIMARY KEY(IDAGENTE,IDEVENTO),
FOREIGN KEY(IDAGENTE) REFERENCES AGENTE(IDAGENTE),
FOREIGN KEY(IDEVENTO) REFERENCES EVENTO(IDEVENTO)
);

-- ---------------------------------
-- CRIACAO TABELA - CLIENTEEVENTO
-- ---------------------------------
CREATE TABLE IF NOT EXISTS CLIENTEEVENTO(
IDCLIENTE INT NOT NULL,
IDEVENTO INT NOT NULL,
PRECOBILHETE DECIMAL(8,2) NOT NULL,
ESTADOPAGAMENTOBILHETE BINARY(1) NOT NULL,
PRIMARY KEY(IDCLIENTE,IDEVENTO),
FOREIGN KEY(IDCLIENTE) REFERENCES CLIENTE(IDCLIENTE),
FOREIGN KEY(IDEVENTO) REFERENCES EVENTO(IDEVENTO)
);

-- ---------------------------------
-- SELECAO - CONTEUDO DAS TABELAS
-- ---------------------------------
SELECT * FROM MORADA;
SELECT * FROM CLIENTE;
SELECT * FROM AGENTE;
SELECT * FROM EVENTO;
SELECT * FROM AGENTEEVENTO;
SELECT * FROM CLIENTEEVENTO;